INSERT INTO attacks VALUES ("Donald Trump", "Only a million","My dad only gave me a small loan of a million dollars", 25);
INSERT INTO attacks VALUES ("Donald Trump", "You're fired","You're FIRED!", 25);
INSERT INTO attacks VALUES ("Donald Trump", "Throw hairpiece","*Donald violently tears his toupe off and hurls it at the opponent*", 25);
INSERT INTO attacks VALUES ("Donald Trump", "elicit passport","Show me your birth certificate", 25);
INSERT INTO attacks VALUES ("Lincoln Chafee", "Happy to be here","I'm just happy to be here", 25);
INSERT INTO attacks VALUES ("Lincoln Chafee", "It's my first day","It's my first day in senate!", 25);
INSERT INTO attacks VALUES ("Lincoln Chafee", "My dad died","My dad just died I just got into senate...", 25);
INSERT INTO attacks VALUES ("Lincoln Chafee", "Well actually..","Well actually...", 25);
INSERT INTO attacks VALUES ("Lincoln Chafee", "Dropout","*Drops out of race*", 25);
INSERT INTO attacks VALUES ("Bernie Sanders", "Violently wave arms","*violent arm movement*", 25);
INSERT INTO attacks VALUES ("Bernie Sanders", "Not a socialist","I am not a socialist (crook)", 25);
INSERT INTO attacks VALUES ("Bernie Sanders", "Tired of hilary's emails","the American people are sick and tired of hearing about Hilary's damn emails!", 25);
INSERT INTO attacks VALUES ("Bernie Sanders", "Middle class is disappearing","The middle class is disappearing!", 25);
INSERT INTO attacks VALUES ("Bernie Sanders", "Free college tuition","Makes public colleges free for all", 25);
INSERT INTO attacks VALUES ("Carly Fiorina", "Woman card","I am a woman *crowd gasps*", 25);
INSERT INTO attacks VALUES ("Carly Fiorina", "Ruin Company","*Absolutely annihilates her own company*", 25);
INSERT INTO attacks VALUES ("Carly Fiorina", "Layoff employees","*Layoff 30,000 people from company*", 25);
INSERT INTO attacks VALUES ("Carly Fiorina", "Send troops","Send the troops!", 25);
INSERT INTO attacks VALUES ("Jeb Bush", "Good genes","I have good genes c'monnnnn", 25);
INSERT INTO attacks VALUES ("Jeb Bush", "Jeb fuel can't melt steel beams","Jeb fuel can't melt steel beams!", 25);
INSERT INTO attacks VALUES ("Jeb Bush", "Question","Do you have a question", 25);
INSERT INTO attacks VALUES ("Jeb Bush", "Not a scientist","I'm not a scientist", 25);
INSERT INTO attacks VALUES ("Jeb Bush", "Stuff happens","Stuff happens", 25);
INSERT INTO attacks VALUES ("Ben Carson", "Jail makes you gay","People that go into prison come out gay", 25);
INSERT INTO attacks VALUES ("Ben Carson", "Obamacare is slavery","Obamacare is the worst thing that has happened in this nation since slavery", 25);
INSERT INTO attacks VALUES ("Ben Carson", "I wouldn't just stand there","I would not just stand there and let him shoot me", 25);
INSERT INTO attacks VALUES ("Ben Carson", "Guns in Germany","If there had been guns in Germany there wouldn't have been a holocaust", 25);
INSERT INTO attacks VALUES ("Ben Carson", "I hate black people","I hate black people", 25);

