UPDATE attacks SET desc="You are going to build a wall and you are\ngoing to pay for it" WHERE desc="You are going to build a wall and you are going to pay for it";
UPDATE attacks SET desc="*Donald violently tears his toupe off and\nhurls it at the opponent*" WHERE desc="*Donald violently tears his toupe off and hurls it at the opponent*";
UPDATE attacks SET desc="Tired of Hillary's emails|the American people are sick and tired of\nhearing about Hillary's damn emails!" WHERE desc="Tired of Hillary's emails|the American people are sick and tired of hearing about Hillary's damn emails!";
UPDATE attacks SET desc="Obamacare is the worst thing that has\nhappened in this nation since slavery" WHERE desc="Obamacare is the worst thing that has happened in this nation since slavery";
UPDATE attacks SET desc="I would not just stand there and let him\nshoot me" WHERE desc="I would not just stand there and let him shoot me";
UPDATE attacks SET desc="If there had been guns in Germany there\nwouldn't have been a holocaust" WHERE desc="If there had been guns in Germany there wouldn't have been a holocaust";
UPDATE attacks SET desc="*Make a terrible closing statement in the\nDemocratic debate*" WHERE desc="*Make a terrible closing statement in the Democratic debate*";
UPDATE attacks SET desc="Lets make America have a 100% clean energy\ngrid by 2050" WHERE desc="Lets make America have a 100% clean energy grid by 2050";
UPDATE attacks SET desc="Net neutrality is the Obamacare of the\ninternet" WHERE desc="Net neutrality is the Obamacare of the internet";
UPDATE attacks SET desc="20 years from now if there is some\nobscure trivial pursuit question I'm sure i'll be\nthe answer" WHERE desc="20 years from now if there is some obscure trivial pursuit question I'm sure i'll be the answer";
UPDATE attacks SET desc="I kinda thought it was the job of the chapel\nto be insensitive to atheists" WHERE desc="I kinda thought it was the job of the chapel to be insensitive to atheists";
UPDATE attacks SET desc="We will not let librals tread on the second\namendment!" WHERE desc="We will not let librals tread on the second amendment!";
UPDATE attacks SET desc="I never, ever cheated. I don't condone cheating.\nBut I would sometimes spread misinformation.\nThis is a great tactic. Misinformation can be very important." WHERE desc="I never, ever cheated. I don't condone cheating. But I would sometimes spread misinformation. This is a great tactic. Misinformation can be very important.";
UPDATE attacks SET desc="I'm gonna make the Oval Office a litte more\n#Chic" WHERE desc="I'm gonna make the Oval Office a litte more #Chic";
UPDATE attacks SET desc="I think ultimately Bengazi was the worst\ntragedy since 9/11" WHERE desc="I think ultimately Bengazi was the worst tragedy since 9/11";
UPDATE attacks SET desc="You may think I'm talking about electing Republicans,\nI'm not, I'm talking about electing lovers of liberty" WHERE desc="You may think I'm talking about electing Republicans, I'm not, I'm talking about electing lovers of liberty";
UPDATE attacks SET desc="Close Fort Lee Bridge Lanes cause Mayor didn't\nendorse me" WHERE desc="Close Fort Lee Bridge Lanes cause Mayor didn't endorse me";
UPDATE attacks SET desc="Even in New Jersey what you're doing is called\nrude" WHERE desc="Even in New Jersey what you're doing is called rude";
