INSERT INTO attacks VALUES ("Jim Webb", "Could I get some time","Could I get some time Anderson", 25);
INSERT INTO attacks VALUES ("Jim Webb", "Dropout","I'm dropping out of the Democratic race", 25);
INSERT INTO attacks VALUES ("Jim Webb", "Already president","I've already won the presidency", 25);
INSERT INTO attacks VALUES ("Jim Webb", "Vietnam","I kicked some ass in Vietnam", 25);
INSERT INTO attacks VALUES ("Martin O'Malley's", "Clean energy","Lets make America have a 100% clean energy grid by 2050", 25);
INSERT INTO attacks VALUES ("Martin O'Malley's", "Get no votes","I have no votes", 25);
INSERT INTO attacks VALUES ("Martin O'Malley's", "Play Banjo","*Plays Banjo*", 25);
INSERT INTO attacks VALUES ("Martin O'Malley's", "Terrible closing","*Make a terrible closing statement in the Democratic debate", 25);
INSERT INTO attacks VALUES ("Hilary Clinton", "Woman president","I would be the first woman president", 25);
INSERT INTO attacks VALUES ("Hilary Clinton", "Not losing again","I'm not losing another presidential race", 25);
INSERT INTO attacks VALUES ("Hilary Clinton", "Take jab at Bernie","Senator Sanders is incorrect and a Socialist", 25);
INSERT INTO attacks VALUES ("Hilary Clinton", "Bengazi","*get interrogated about Bengazi-attack", 25);
INSERT INTO attacks VALUES ("Ted Cruz", "Net Neutrality","Net neutrality is the Obamacare of the internet", 25);
INSERT INTO attacks VALUES ("Ted Cruz", "Thanks Obama","Thanks Obama", 25);
INSERT INTO attacks VALUES ("Ted Cruz", "I will be a trivia pursuit answer","20 years from now if there is some obscure trivial pursuit question I'm sure i'll be the answer", 25);
INSERT INTO attacks VALUES ("Ted Cruz", "Religion card","I kinda thought it was the job of the chapel to be insensitive to atheists", 25);
INSERT INTO attacks VALUES ("Ted Cruz", "Oh Canada","OH CANADAAAAAA", 25);
INSERT INTO attacks VALUES ("Ted Cruz", "Whacko bird","I am a very very proud whacko bird", 25);
